### ISSUE TITLE
Long running queries/expired recalls

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/ids.server#115]
This has been somewhat of an ongoing problem on the Diamond ICAT system that has been investigated previously but never resolved.

The problem occurs when a user submits a download/restore request via TopCAT. TopCAT then passes the request on to the IDS in the form of a prepareData call and waits for the IDS to respond with a preparedID. What happens next is that the IDS takes longer than the 30 minute timeout to respond, so TopCAT does not get a preparedID and cannot progress the request. (Just as a side note increasing the 30 minute timeout is not really a suitable/sustainable option because some of the requests take hours to complete and the request really should not take more than 30 minutes).

The problem tends to occur for InstrumentScientists who have access to a lot of data but has also been seen for InvestigationUsers who also have access to many Investigations.

From a recent investigation, our database admin identified the following query which had been running on the database for a long time:

`SELECT *
FROM
(SELECT a.*, ROWNUM rnum
FROM
(SELECT t0.ID AS a1, t0.NAME AS a2, t0.LOCATION AS a3, t0.CREATE_ID AS a4, t0.MOD_ID AS a5
FROM DATAFILE t0
WHERE ((((t0.DATASET_ID = :1 ) AND (t0.LOCATION IS NOT NULL)) AND (t0.ID BETWEEN :2 AND :3 )) AND ((t0.ID IN
(SELECT t1.ID
FROM INVESTIGATION t3, DATASET t2, DATAFILE t1
WHERE ((t3.VISIT_ID IN (:4 , :5 )) AND ((t2.ID = t1.DATASET_ID) AND (t3.ID = t2.INVESTIGATION_ID)))) OR t0.ID IN
(SELECT DISTINCT t4.ID
FROM INVESTIGATIONINSTRUMENT t7, INVESTIGATION t6, DATASET t5, DATAFILE t4, USER_ t10, INSTRUMENTSCIENTIST t9, INSTRUMENT t8
WHERE ((t10.NAME = :6 ) AND ((((((t5.ID = t4.DATASET_ID) AND (t6.ID = t5.INVESTIGATION_ID)) AND (t7.INVESTIGATION_ID = t6.ID)) AND (t8.ID = t7.INSTRUMENT_ID)) AND (t9.INSTRUMENT_ID = t8.ID)) AND (t10.ID = t9.USER_ID))))) OR t0.ID IN
(SELECT DISTINCT t11.ID
FROM INVESTIGATION t13, DATASET t12, DATAFILE t11, USER_ t15, INVESTIGATIONUSER t14
WHERE ((t15.NAME = :7 ) AND ((((t12.ID = t11.DATASET_ID) AND (t13.ID = t12.INVESTIGATION_ID)) AND (t14.INVESTIGATION_ID = t13.ID)) AND (t15.ID = t14.USER_ID))))))) a
WHERE ROWNUM <= :8 )
WHERE rnum > :9
`

This is the result of the ICAT query at the following line in the manyDfs method of DataSelection being executed:
https://github.com/icatproject/ids.server/blob/v1.11.0/src/main/java/org/icatproject/ids/DataSelection.java#L247

The query in the code is simple enough but by the time it has had the InstrumentScientist and InvestigationUser "where" clauses added (along with another rule we have for some open data) the final query is rather complicated. 

Along with the complexity of the query, the number of results returned can vary between 1 and 250,000 (the maxEntities value of the ICAT) so it is thought that Oracle struggles to select an appropriate execution plan for the query.

The workaround at the moment is for the service manager to spot in the TopCAT admin tab when there is a user download in this state and to use a specially prepared script which generates a preparedID from the IDS using the login details for an ICAT root user and inserts it into TopCAT. Using a root user account means that none of the ICAT rules get added to the ICAT query and the final query that goes to the database is almost as simple as the query in the IDS code. Thus the preparedID is generated extremely quickly.

**Comment by RKrahl** [comment]
I added some line breaks and indentation to the query to better understand the structure:
```sql
SELECT * FROM (SELECT a.*, ROWNUM rnum FROM (
    SELECT t0.ID AS a1, t0.NAME AS a2, t0.LOCATION AS a3, t0.CREATE_ID AS a4, t0.MOD_ID AS a5 FROM DATAFILE t0 WHERE (
        (
            ((t0.DATASET_ID = :1 ) AND (t0.LOCATION IS NOT NULL)) AND (t0.ID BETWEEN :2 AND :3 )
        ) AND (
            (t0.ID IN (
                SELECT t1.ID FROM INVESTIGATION t3, DATASET t2, DATAFILE t1 WHERE ((t3.VISIT_ID IN (:4 , :5 )) AND ((t2.ID = t1.DATASET_ID) AND (t3.ID = t2.INVESTIGATION_ID)))
            ) OR t0.ID IN (
                SELECT DISTINCT t4.ID FROM INVESTIGATIONINSTRUMENT t7, INVESTIGATION t6, DATASET t5, DATAFILE t4, USER_ t10, INSTRUMENTSCIENTIST t9, INSTRUMENT t8 WHERE ((t10.NAME = :6 ) AND ((((((t5.ID = t4.DATASET_ID) AND (t6.ID = t5.INVESTIGATION_ID)) AND (t7.INVESTIGATION_ID = t6.ID)) AND (t8.ID = t7.INSTRUMENT_ID)) AND (t9.INSTRUMENT_ID = t8.ID)) AND (t10.ID = t9.USER_ID)))
            )) OR t0.ID IN (
                SELECT DISTINCT t11.ID FROM INVESTIGATION t13, DATASET t12, DATAFILE t11, USER_ t15, INVESTIGATIONUSER t14 WHERE ((t15.NAME = :7 ) AND ((((t12.ID = t11.DATASET_ID) AND (t13.ID = t12.INVESTIGATION_ID)) AND (t14.INVESTIGATION_ID = t13.ID)) AND (t15.ID = t14.USER_ID)))
            )
        )
    )
) a WHERE ROWNUM <= :8 ) WHERE rnum > :9
```

There is an outer wrapping of the query in two nested `SELECT` clauses that I guess have been added somewhere in the database backend.  Inside this wrapping we recognize the original query having two conditions combined with `AND` in the `WHERE` clause, the first one is the original condition and the second one apparently comes from the access rules added in `icat.server`.  The latter in turn is a combination of three `SELECT` clauses, apparently originating from three rules that have been taken into account.

The original condition is rather harmless.  The trouble seem to come from the rule mechanism in `icat.server` and, as you report, from the fact that the sub queries yield a very large number of results.

**Comment by kevinphippsstfc** [comment]
Yes, I think what you say is entirely correct. Apologies for not formatting the query myself. It is much easier to understand in your reformatted version.

**Comment by RKrahl** [comment]
There is another observation: the core of the problem seem to be the combination of two issues: a rather complex query resulting from applying the access rules in `icat.server` and the fact that you have a huge number of datafiles at DLS. But if we taker a closer look at the conditions that come from the rules in that query, they do not depend on datafiles at all.  They only depend on the investigations that the user is allowed to see.  But for these investigations we certainly get a much smaller number.

So if we could search for the investigations that the user is allowed to see in a first step and then search for the datafiles related to these investigations in a second step, that might have a much better performance, because the complexity of the query is only in the first step and the huge number of objects only in the second one.  I know that there is no obvious way to do that with the current authorization mechanism in `icat.server`. But it might point into the direction where to search for a solution.
