### ISSUE TITLE
REST API getSize fails for very large investigations

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/ids.server#23]
The getSize REST API  call for a very large investigation can fail. This is usally accompanied with a  GC overhead limit exceeded on the ICAT server or an entities limit reach error.

The ids responses with a status code of 500 with the following content: 

    "{\"code\":\"InternalException\",\"message\":\"class org.icatproject.IcatException_Exception INTERNAL org.icatproject.core.IcatException\"}"

Example investigation id on facilities02 that failed includes:

investigationIds=483541493
investigationIds=576503052
investigationIds=908730626
investigationIds=576503051
investigationIds=908730627
investigationIds=576503053

Note: The above 6 calls failed out of 50 requests that were made at the same time.

**Comment by fisherab** [comment]
The problem is that the DataSelection object in the ids.server needs protection against very large investigations.
