### ISSUE TITLE
InternalError is raised if datafileCreateTime parameter is set to rubbish in put method

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#31]
If the client calls the IDS put method with rubbish in the datafileCreateTime parameter (such as a time string in place of milliseconds since epoch), the server raises an `InternalException`:
```python
>>> createTime = '2008-06-18 09:31:11+00:00'
>>> with open(fname, "rb") as f:
...   client.ids.put(f, os.path.basename(fname), 
...                  dataset.id, datafileformat.id, 
...                  datafileCreateTime=createTime)
... 
Traceback (most recent call last):
  ...
icat.exception.IDSInternalError: class org.glassfish.jersey.server.ParamException$QueryParamException HTTP 404 Not Found
```
An error traceback is written to [ids.log](https://gist.github.com/RKrahl/dd65011d3589b397dcb4#file-ids-log).

Obviously, raising an error here is justified.  But it should rather be something like `BadRequestException`.

This issue became apparent by a client error, icatproject/python-icat#10.  See also the discussion in the icatgroup mailing list.

**Comment by fisherab** [comment]
I have reproduced the error

**Comment by fisherab** [comment]
test written in the ids.client as the ids.server tests are in java and so cannot produce an invalid date/time format

**Comment by fisherab** [comment]
The ids.server is expecting a Java Long to be passed in. This is processed by Jersey which throws an org.glassfish.jersey.server.ParamException$QueryParamException which I then get catch by an ExceptionMapper<RuntimeException> and I assume that RuntimeExceptions are internal IDS errors. To fix it I need to make the code expect a string rather than a long and then convert it myself. This is less elegant - but will trap the error!

**Comment by RKrahl** [comment]
Without having looked into the code, couldn't you just drop the assumption that RuntimeExceptions are internal IDS errors?  E.g. inspect the RuntimeException and raise either parameter error or internal error depending on the findings?

**Comment by fisherab** [comment]
Not really because I don't want to depend upon Jersey. WildFly uses RestEasy to do the same job.
