### ISSUE TITLE
Archive restore failure

### ISSUE THREAD

**Issue by frazzleuk** [icatproject/ids.server#33]
If a file from secondary storage (tape) fails to restore, the IDS will keep trying to restore it forever and the state will stay as RESTORING.

**Comment by tomgriffinstfc** [comment]
THere should be a mechanism to alert the user that the retrieval failed, in a similar way to download ready emails. This is likely to be a TopCAT function, so when this ticket is fixed a new TopCAT ticket should be raised.

**Comment by fisherab** [comment]
I plan to use a map which will be added to whenever there is a restore failure and where the entry will be removed whenever a restore is successful. Calls to getData and getStatus will look at this map and throw an InternalException if the entry is found. The restore will carry on looping. 

The solution to issue #41 will allow the restore request to be cancelled

**Comment by fisherab** [comment]
The IDS does not loop trying to restore. A restore request is typically provoked by topcat calling isPrepared.  The IDS will, when the new code is added, throw an exception with calls to getStatus and isPrepared if one of the restores has failed. The flag for each dataset or datafile can be cleared by a new call reset() which takes either preparedId or a DataSelection. Any getData calls will proceed as normal and if a succesful restore is performed will clear the flag.
