### ISSUE TITLE
Download logging via JMS

### ISSUE THREAD

**Issue by Softey** [icatproject/ids.server#38]
The IDS should make available download metadata via JMS. 

This is to allow the Dashboard to collect metadata on downloads carried out by the IDS.

It should send out messages on the following events:

- Prepare Download

- Download start

- Download end

An example for a prepare download message:

Properties:
      - Operation: Prepare Download
      - User: (name) uows/123456 OR (user_id) 6781123 
      - IP Address: 192.168.0.1
Body:
      {"datasetIds”:[123456],”datafileIds”:[14513243],”preparedID”:”23fw2c2312-r2f222f2c-2f2ty2y23”}

An example for a download start:

Properties:
     - Operation: Download Start
     - Time: 2015-10-10 12:01:01

Body:
     {”preparedID”:”23fw2c2312-r2f222f2c-2f2ty2y23”}

Download end would just change the operation value and a new field should be added to say if the download completed or was stopped before it could finish.

As you can see the bulk of the information would be in the prepare data with the download start and end acting as flags.

**Comment by fisherab** [comment]
I have now implemented this for all calls and tested with a simple MDB which reports:

    String operation = om.getStringProperty("operation");
    String ip = om.getStringProperty("ip");
    long millis = om.getLongProperty("millis");
    String body = om.getText();

some example outputs are:

    archive 130.246.76.95 {"userName":"db/root","datasetIds":[2464]} took 27ms
    delete 130.246.76.95 {"userName":"db/root","datasetIds":[2472]} took 74ms
    getData 130.246.76.95 {"preparedId":"882c75d3-82d5-4e1d-b3ca-c09198c5d12a"} took 10ms
    getData 130.246.76.95 {"userName":"db/root","datafileIds":[4971]} took 19ms
    getData 130.246.76.95 {"userName":"db/root","investigationIds":[1593]} took 140ms
    getDatafileIds 130.246.76.95 {"preparedId":"c4921bde-2e41-48f1-8ed3-2dbd49c5ee3a"} took 4ms
    getDatafileIds 130.246.76.95 {"userName":"db/root","datafileIds":[4739]} took 18ms
    getIcatUrl 130.246.76.95 {} took 1ms
    getLink 130.246.76.95 {"userName":"db/root","datafileId":4837} took 32ms
    getServiceStatus 130.246.76.95 {"userName":"db/root"} took 8ms]
    getSize 130.246.76.95 {"userName":"db/root","datafileIds":[5013,5014,5015,5016]} took 107ms
    getStatus 130.246.76.95 {"userName":"db/root","datafileIds":[5376,5377,5378,5375]} took 89ms
    getStatus 130.246.76.95 {"userName":"db/root","datasetIds":[2638]} took 30ms
    isPrepared 130.246.76.95 {"preparedId":"7ea94fb5-1053-4e7c-90ef-a47f51140758"} took 2ms
    isReadOnly 130.246.76.95 {} took 1ms
    isTwoLevel 130.246.76.95 {} took 0ms
    prepareData 130.246.76.95 {"userName":"db/root","datafileIds":[5089],"preparedId":"09a5cc75-cd89-4eff-9197-44cf814e3b7f"} took 40ms
    put 130.246.76.95 {"userName":"db/root","datafileId":4797} took 57ms
    restore 130.246.76.95 {"userName":"db/root","datasetIds":[2475]} took 31ms
    restore 130.246.76.95 {"userName":"db/root","datasetIds":[2484],"datafileIds":[4927]} took 73ms

It should be noted that I have minimised the output. I have not transmitted the start time of an operation as the bean can note when it received the message. If wished I can add this in very easily.

Logging is controlled by the a new entry in ids.properties log.list which contains a space separated list of keywords indicating classes of call these are:

 - INFO getStatus, isPrepared etc.
 - READ   getData
 - WRITE  put
 - MIGRATE restore and archive
 - LINK getLink
 - PREPARE prepareData

The keywords READ and WRITE have been chosen to allow a similar scheme to be added to the icat.server.
