### ISSUE TITLE
Calling restore on a dataset if DsRestorer is already running triggers a second restore

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#40]
If a restore request is called on a dataset while the `DsRestorer` is already restoring it, a second `RESTORE` op is queued. As a result, as soon as the first restore is finished, another `DsRestorer` is started, trying to restore the dataset again.  The zip file is copied again from archive storage and the `DsRestorer` tries to extract the datafiles from it. At his point, the second restore failed with a `FileAlreadyExistsException` in my test, but this depends on the storage plugin, whether the implementation of `mainStorage.put(InputStream, String)` allows overwriting of existing files. The useless second restore may take a significant amount of time, depending on the size of the dataset. The status of the dataset remains `RESTORING` during this time.

To reproduce:
```python
>>> selection = icat.ids.DataSelection([dataset])
>>> client.ids.getStatus(selection)
u'ARCHIVED'
>>> client.ids.restore(selection)
>>> time.sleep(2)
>>> client.ids.getStatus(selection)
u'RESTORING'
>>> client.ids.restore(selection)
```
See the corresponding [ids.log](https://github.com/icatproject/ids.server/files/106693/ids.log.txt) that shows that restoring is started again after it already has been completed at 15:14:43.

I suggest that the restore call should check the status of the selected objects and should do nothing unless this status is `ARCHIVED`.

I don't know if this issue is related to #33. The setting and the observations are somewhat different, so I start a new issue.

**Comment by fisherab** [comment]
I think I had a reason for that - I will have a think

Steve

**Comment by fisherab** [comment]
I agree that this behaviour is potentially inefficient. It could easily be worked around in the plugin which must already  implement the exists() function. I will fix it in the IDS though I am not sure where is the best place to do it. I like to be able to deal with a client making a series of restore calls. The getStatus logic can be quite slow for a very big DataSelection so I prefer to process the request via the FSM and then only when I come to process the queue use the logic inside getStatus() to decide whether or not any action is actually necessary.

**Comment by RKrahl** [comment]
As I mentioned in the January meeting, I found race conditions in IDS.  I positively documented them, but I need more time to investigate the possible combinations and the severity in each case.  Obviously, this is not simple, as everything depends on timing and it's not easy to reliably reproduce and analyse an issue that has been observed once.

In any case this restore issue is just a kind of a special case of a greater picture.  I have some ideas on it, but I need to do my homework first, before I can present this for discussion.  Unfortunately, I was busy with other things lately.  I would not mind if you want to postpone this restore issue until then.
