### ISSUE TITLE
Transfer ID is not incremented correctly

### ISSUE THREAD

**Issue by Softey** [icatproject/ids.server#45]
Currently at the moment the behaviour is as follows:

The JMS flow for a "**full prepare download**":

prepareData
getDataStart
getData

The transferId will stay at 0. 

The JMS flow for a "**direct download**":

getDataStart
getData

The transferId will increment by 1. 

If I do a  "**full prepare download**": after the transfer ID has been incremented by a  "**direct download**" then the transferId gets reset to 0. 

It seems that a "**full prepare download**" keeps resetting the transferId and won't increment it.

**Comment by fisherab** [comment]
I forget to indicate that this has been fixed. A variable should have been declared to be static but wasn't. Now it should be fine.
