### ISSUE TITLE
getSize not working

### ISSUE THREAD

**Issue by jodysalt** [icatproject/ids.server#46]
The following didn't work (for the 1.6 snapshot):

https://idsdev2.isis.cclrc.ac.uk/ids/getSize?server=https:%2F%2Ficatdev15.isis.cclrc.ac.uk&sessionId=fffdd093-0ac0-41b6-92f0-ab0d3a1fb905&investigationIds=64302434

got:

{"code":"InternalException","message":"class javax.ejb.TransactionRolledbackLocalException Exception thrown from bean: java.lang.NoClassDefFoundError: Could not initialize class org.icatproject.ids.DataSelection"}

**Comment by fisherab** [comment]
This is most likely caused by the plugin interface. If you used 1.3.0 then please try 1.3.1-SNAPSHOT instead

**Comment by Softey** [comment]
I updated the ids plugin from 1.3.0 to the 1.3.1-SNAPSHOT and I unfortunately still receive the following error:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class                         org.icatproject.ids.DataSelection
at org.icatproject.ids.IdsBean.getSize(IdsBean.java:1120)
```

**Comment by fisherab** [comment]
I still think it is because your plugin has directly or indirectly a
dependency upon the icat client. Check the version of icat-utils. I think
you want 4.13.0-snapshot. Otherwise it will have to wait till next week.

**Comment by Softey** [comment]
The plugin does have a dependency on the ICAT.client but only for the testing of the plugin. I changed the dependency scope to test so it is no longer built with the deployed plugin. I also upgraded the icat-utils to 4.13.0-snapshot. 

With those changes in the pom in the plugin the ids.server no longer throws the NoClassDefFoundError and the getSize call now works.
