### ISSUE TITLE
getSize call now takes a while to return a value

### ISSUE THREAD

**Issue by Softey** [icatproject/ids.server#53]
A getSize call on even a small dataset is taking a lot longer then before. 

The call below took 8 minutes to resolve.

The database I am using for the ICAT is Oracle 12.

The following is generated for a getSize call on a single dataset:

JPQL generated:

SELECT  df FROM Datafile df WHERE (  df.dataset.id = 49770050 AND df.id > -1 )  ORDER BY df.id

Oracle SQL generated:

SELECT * FROM (SELECT /*+ FIRST_ROWS */ a.*, ROWNUM rnum  FROM (SELECT ID AS a1, CHECKSUM AS a2, CREATE_ID AS a3, CREATE_TIME AS a4, DATAFILECREATETIME AS a5, DATAFILEMODTIME AS a6, DESCRIPTION AS a7, DOI AS a8, FILESIZE AS a9, LOCATION AS a10, MOD_ID AS a11, MOD_TIME AS a12, NAME AS a13, DATAFILEFORMAT_ID AS a14, DATASET_ID AS a15 FROM DATAFILE WHERE ((DATASET_ID = 49770050) AND (ID > -1)) ORDER BY ID) a WHERE ROWNUM <= 150000) WHERE rnum > 0

A value is eventually returned but the above dataset that is queried only has 295 files

**Comment by fisherab** [comment]
This is now covered by icatproject/icat.utils#3
