### ISSUE TITLE
getLink to accept multiple datafile ids

### ISSUE THREAD

**Issue by frazzleuk** [icatproject/ids.server#55]
Allow the getLink method to accept a list of datafile ids where it will then return a list of hardlinks.

**Comment by fisherab** [comment]
This will be delayed until such time as it is evident that it will bring benefits

**Comment by RKrahl** [comment]
Is this still relevant? I tend to close as `wontfix`.

**Comment by RKrahl** [comment]
No news since several months.  Seems not to be relevant.
