### ISSUE TITLE
IOErrors from the plugin should be logged

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#57]
When a storage plugin call throws an IOError, an InternalError is reported to the client, so far so good.  But no trace of the incident is written to the log file.  I'd expect logging of the error because it is most likely hints to a severe problem that the ICAT admin should get noticed about.

**Comment by fisherab** [comment]
Some of the calls do result in a call to logger.error - but presumably not all. I will go through and check for missing ones.
