### ISSUE TITLE
prepareData request fails for mx9948-62

### ISSUE THREAD

**Issue by jodysalt** [icatproject/ids.server#62]
Sending all the datasets ids in visit 1367913229 to the IDS prepareData call fails

**Comment by jodysalt** [comment]
go to https://icat.diamond.ac.uk/#/browse/facility/DLS/proposal/MX9948/investigation/1367913229/dataset

Add all datasets to cart, then submit it for download.

**Comment by jodysalt** [comment]
Got a slight suspicion this might have something to do with the problem:

https://icat.diamond.ac.uk/#/browse/facility/DLS/proposal/MX9948/investigation/1367913229/dataset/1364437620/datafile

(one dataset in this visit)

:-)

**Comment by jodysalt** [comment]
If I try to run a getSize on the above dataset I get:

curl https://ids01.diamond.ac.uk/ids/getSize?server=https:%2F%2Ficat02.diamond.ac.uk&sessionId=your_session_id&datasetIds=1364437620

I get:

{"code":"InternalException","message":"class org.icatproject.IcatException_Exception attempt to return more than 250000 entitities"}

then if I run  a prepareData on the above dataset I get:

curl --data "sessionId=your_session_id&datasetIds=1364437620" https://ids01.diamond.ac.uk/ids/prepareData

I get the same error.

**Comment by jodysalt** [comment]
I think I have found the problem.

The IDS is trying to do an ICAT 'properties' call to determine the maxEntities it can return back. However, the ICAT it is pointing to (version 4.5.0 https://icat01.diamond.ac.uk)  doesn't implement this 'properties' call.

So I'm guessing org.icatproject.ids.PropertyHandler.getMaxEntities is falling over and returning 0.

So if something like following is run:

select dataset from Dataset dataset, dataset.investigation as investigation where investigation.id = 1879876375 limit 0, 0

It returns all the rows.

Since dataset 1364437620 has over 450,000 files it breaks this 250,000 limit.

**Comment by fisherab** [comment]
This ids in use was version 1.5 which does not ask icat for maxEntitities so this problem will continue for DLS until we move to IDS 1.7

**Comment by fisherab** [comment]
This ids in use was version 1.5 which does not ask icat for maxEntitities so this problem will continue for DLS until we move to IDS 1.7
