### ISSUE TITLE
Test suite should not create any files or directories in ${HOME}

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#75]
When running the tests, some files and directories are created with hard coded names in the home directory of the user running the tests.  In many cases, it is inappropriate at best to do that and I did not find any way in the configuration to change this behavior.  I needed to edit the following source files to get rid of this:
```
src/main/resources/logback.xml
src/main/resources/run.properties
src/test/resources/one.properties
src/test/resources/two.properties
src/test/resources/twodf.properties
```
But locally editing these file is also not really a solution, because it is very inconvenient not being able to run the tests in a clean working directory.  I suggest something like adding a setting `testHome` in `~/.m2/settings.xml` that should be used to substitute `${HOME}` during the tests.  This may also be a place to put the `reliability` file.

**Comment by fisherab** [comment]
I agree - I hope to add it to 1.9.0
