### ISSUE TITLE
Uncaught exception in DfRestorer can cause restoration to stall until IDS is restarted

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/ids.server#87]
During processing DataFile restores in the DfRestorer thread, the Diamond IDS storage plugin threw an IndexOuOfBoundsException. The exception was not caught so the call to fsm.removeFromChanging was never made and the locks were never released. The file restoration was only able to complete after the IDS was restarted.

In DfRestorer.java, the calls to the plugin are protected by a catch (IOException e) - see [here](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/thread/DfRestorer.java#L79) The equivalent code in the other Runnables the thread directory (eg. [here](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/thread/DsRestorer.java#L110)) catch an Exception.

I propose:
a) That the DfRestorer code is refactored to a try... catch(Exception e) ... finally structure to match the other Runnable classes.
b) That the contents of the run() method of each of the Runnables be wrapped in a try ... finally clause with the lock releases moved to the finally block.

**Comment by RKrahl** [comment]
Yes, this is pretty obvious a bug.  I also agree with your suggestions.
