### ISSUE TITLE
Tidier does not escape file paths

### ISSUE THREAD

**Issue by stuartpullinger** [icatproject/ids.server#92]
The [Tidier](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/Tidier.java) uses string concatenation to assemble a query about Datafiles. This fails for file paths which contain, for example, a single quote character.

In Tidier.java, at [line 129](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/Tidier.java#L129), there is a call to [addStringConstraint](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/Tidier.java#L173) which assembles the string using [simple concatenation](https://github.com/icatproject/ids.server/blob/master/src/main/java/org/icatproject/ids/Tidier.java#L194).

I see errors in my ids.log like this:
```
2018-11-29 06:07:01,546 ERROR [Timer-3] Tidier$Action 161 - class org.icatproject.IcatException_Exception Unexpected end of string in state INQUOTES for string: SELECT df FROM Datafile df WHERE df.location = '/dls/ixx/data/2018/xx12345/processing/scripts/Alice's script/Bob_ExtractTiff_flats.py' INCLUDE df.dataset LIMIT 0,500
```

We should wrap the `df.location` on line 129 in some sort of escaping function - I'm not sure what yet.

**Comment by RKrahl** [comment]
You allow shell meta characters in file names? Seriously?

**Comment by stuartpullinger** [comment]
What can I say? I'm not proud 😞 but they exist in a database here.  I haven't fully tested this yet, but I presume that, since the files have made it all the way to the Tidier stage, the path is handled differently elsewhere in the code. I may not have time to test this for a while (Jury Service next week).

**Comment by stuartpullinger** [comment]
This is looking like a tricky problem to solve.

The hacky way to solve this is to replace all single-quote characters with 2 single-quotes - this is the proper way to escape this character as far as I can see. But this does not remove all possible SQL injections.

The proper way to do this is to create a parameterised query. Unfortunately, once this is created, it doesn't seem possible to get the full JPQL query back out again - and we need to get a string here so we can append Steve's additional JPQL syntax for LIMIT and INCLUDE and pass this on to other methods.

Perhaps we can create the query as a string with named parameter placeholders and pass around an additional mapping type with the query string. Then, when it is time to actually call the query, the mapping can be used to fill in the parameters. My first impression is that I'm not very keen on this approach but it might be pragmatic.

**Comment by RKrahl** [comment]
For ids.server, it's even worse then that. It needs transform the query to a string to pass it to icat.server in the API call. It has no way to actually call the query. Furthermore ids.server has no direct connection to the database backend. So, as far I understand the things, there is no PersistenceContext and thus no way to use the Query class from the Java Persistence API.

**Comment by RKrahl** [comment]
Thanks for the patch!

Obviously, it is just a hotfix that fixes the current apostrophe problem, but not the general issue of needing to escape JPQL meta characters in general and in all values taken from the database. For the latter, I'd suggest to add some JPQL query builder class in icat.utils. One might want to have a look on [the corresponding class in python-icat](https://icatproject.org/misc/python-icat/doc/0.14.1/query.html) for a rough idea how the API of such a class may look like. The query should accept parameterized values in the conditions. The escaping should then be done in that class, when serializing the query to a string. Besides solving the escaping issue, this would also help to get rid of some very clumsy code that we have at various places when building queries out of several conditions.
