### ISSUE TITLE
DsRestorer: missing error handling in the case of a corrupt ZIP archive

### ISSUE THREAD

**Issue by RKrahl** [icatproject/ids.server#96]
If the storage unit is dataset, data in archive is stored as a ZIP file per dataset. This ZIP file must contain one entry for each datafile in the dataset with the name equal to `datafile.name`. There must be no other entries in the ZIP archive.

`DsRestorer` blindly relies on the ZIP file to be correct in the sense pointed out above. It is lacking proper error handling. In the case of spurious entries in the ZIP archive, it will call `mainStorage.put()` with a `null` location value.

**Comment by RKrahl** [comment]
This is in a sense a regression introduced by 145c8b5 in the context of #63 and #83.

The previous behavior in 1.8.0 and older was logging an error and otherwise ignoring the spurious entry. I rather tend to raise an exception at this point, which would result in a complete failure of the restore.

**Comment by stuartpullinger** [comment]
I'm not sure that throwing an exception is the correct approach for the cases of duplicate or spurious entries. Wouldn't it be better to log an error? This way, the user still gets the data they asked for and it is up to the administrator to resolve the problem.

We don't use Dataset-level archive storage at this site but maybe Alex will have a view.

**Comment by RKrahl** [comment]
A ZIP file in archive that does not contain the same files that are to be expected according to the content of ICAT, that is something that should never happen. It means that there is something very fundamentally going wrong with that dataset. I'd say, it requires intervention of the admin. In particular all automatic processing of this dataset should be set on hold until the corrupt data is repaired. If we only log an error and allow the restore the proceed, subsequent calls may be done on that dataset which may further increase the damage.

Just one scenario as an example: imagine the ZIP in archive to be correct, but accidentally one datafile has been deleted from the dataset in ICAT. At this stage, the error could still easily be repaired, you just need to resurrect the datafile in ICAT and everything is fine. But if we allow the restore to proceed despite the error, that dataset will be extracted omitting the datafile. Now the user may upload another datafile to the dataset.  This will trigger a write in IDS, which will eventually overwrite the ZIP file in archive storage. At this point, the missing datafile will be gone for ever and no-one will even notice the problem.

I'd further argue, it is better to provide no data then to provide wrong data. If we just log the error, the user will get no notice about that. So the user will download the dataset, assuming it to be correct and complete. Working on these damaged dataset may inflict more damage on the user's side as a result.

**Comment by antolinos** [comment]
Hi,

Even if I might agree that this should never happen, It happens. 

It is not rare to find dataset which file(s) has been removed from disk after the dataset's creation dataset in ICAT but before the archiving process to start. 

In this case an sysadmin can not do anything as file(s) is lost. However we would like to have as much as possible of this dataset to be archived.

Our approach is to do the best effort. It means that dataset will be archived and will contain only the files that are available at the time a dataset was archived. 
Of course, then it might happen that there is a discrepancy between the datafiles stored in ICAT and the files stored in a zip.

So, I mostly agree with @stuartpullinger

**Comment by RKrahl** [comment]
@antolinos, two remarks:

1. the scenario you describe does not match this issue. If the storage is inconsistent with the content of ICAT because files are removed from disk before writing the archive, it will be the DsWriter that runs into the error and the archive file will not even be created. This issue is about error handling in the DsRestorer. 

2. even if we assume that inconsistencies between ICAT and storage may occur, the question is what to do in such a situation. I hope you agree that such inconsistencies must be repaired and that it is not the acceptable behavior to do nothing about it and watch the subsequent damage to grow. Repairing requires intervention of the admin. To allow this intervention to happen, we must first halt automatic processing of the concerned dataset.

**Comment by antolinos** [comment]
Hi @RKrahl ,

Sorry, not sure if I follow you. In my scenario DsWriter is not used and datafiles are created directly into ICAT and then archived by other process that it is not IDS.

This issue says:
```
DsRestorer blindly relies on the ZIP file to be correct in the sense pointed out above.
```
and above is:
```
This ZIP file must contain one entry for each datafile in the dataset with the name equal to datafile.name
```
In my scenario, the ZIP file will not contain one entry for each datafile in the dataset.
In this situation we would prefer to get a uncomplete zip rather than nothing (in case IDS rises an exception)

**Comment by RKrahl** [comment]
@antolinos, if you don't use the DsWriter and create the archive files by another process, then this process must still create valid and consistent archive files. E.g. it must make sure that the file in archive storage is consistent with the content in ICAT. If a file is lost from disk before writing the archive then there is probably no other way then to accept this as a fact. But that means, it must also be reflected in ICAT accordingly, by either deleting the corresponding datafile object from ICAT or at least clearing the location attribute of that object.

And yes, you cite correctly, DsRestorer should not blindly rely on the ZIP file to be correct. It must verify this and throw an error it this is not the case.  And no, just keeping things in an inconsistent state is not an option and will not work.

**Comment by RKrahl** [comment]
We discussed this in the last meeting, 28. March, but as far as I remember, we didn't draw a final conclusion. Now I would like to release 1.10 this week and this issue is the last obstacle that need to be resolved.

As I pointed out in the discussion, ids.server relies in many situations on the content of ICAT to be in line with the storage. If this consistency is not provided, ids.server will not work correctly and you will get many problems, not only in the DsRestorer. @antolinos, are you happy with my suggestion to re-establish this consistency by clearing the location attribute in Datafiles that are not present in the storage (any more)? This could also be a helpful indicator for the user, to distinguish Datafiles that actually exist from those that don't.

**Comment by antolinos** [comment]
Hi @RKrahl 

If I want to clear the location attribute I would first need to restore all datasets from tape, unzip them and check each file,  that is something that could take... ages. Today we don't have anything in place to make such massive restoration.

I have also to admit that I am not happy by removing the location attribute. It gives a valuable information to the users that helps to locate their data later on in some cases. I know you told that meaning of location was not intended to be "location" but something else managed by the IDS.  
I remind the documentation of ICAT: https://repo.icatproject.org/site/icat/server/4.8.0/schema.html#Datafile
**Location: The logical location of the file - which may also be the physical location**

In any case and unfortunately, today I got 200M records that use location in the sense of physical location and I have to say that it does what we expect. I wonder if It is not a pity that DataFile table did not contain two columns for physical and logical location.

Moreover, I can imagine some use cases where files produced by the experiment will not be archived for different reasons and:
1) I would still like users to download their data (at least the files that are not missing). It is not acceptable for us to get an error if a file is missing.
2) I would need to list the files as produced by the experiment and the most important value is the location

Our only requirement is that ICAT should be consistent with the data and metadata produced in a experiment and not necessarily with the secondary storage.

Once said this and taking into account that it is a problem specific with the way we are using ICAT and IDS here:
If there is no a better option, I would find sensible for the project in general and the IDS in particular that that consistency is enforced as It seems to be crucial for the correct behavior of the IDS.
If IDS triggers an error the only thing, we could do, is:
a) Stick to version IDS 1.9.0
b) Implement a "sort of" light IDS as our use case is much more simple.

Probably option b is more realistic at long term.

**Comment by RKrahl** [comment]
@antolinos,

I'm afraid, option "a", sticking with ids.server 1.9.0, will not work for you. I can only repeat myself: the assumption that the content of ICAT is consistent with the storage is very fundamental to ids.server and taken more or less everywhere throughout the code. This holds for all versions of ids.server. Just one example: lets assume you use ids.server 1.9.0, ignored the error from `DsRestorer` and got the incomplete zip file from archive restored to main storage. Now, the user might want to download that dataset. This will even (apparently) work: the user makes the `getData` call, ids.server will reply with HTTP Ok (200) and a zip file in the body. But if the user inspects the downloaded file closer, he or she will get:
```
$ file /tmp/testdata.zip  
/tmp/testdata.zip: Zip archive data, at least v2.0 to extract Zip archive data, at least v2.0 to extract
$ unzip -l /tmp/testdata.zip
Archive:  /tmp/testdata.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/testdata.zip or
        /tmp/testdata.zip.zip, and cannot find /tmp/testdata.zip.ZIP, period.
```
See #100 for an explanation. Note that this (partial) download may still be large. I guess your users will not be very happy if they waited an hour for downloading a few tens of GB just to find out that all they got in the end is a very large, but unusable pile of bits.

I'm very sorry, but if you insist to use ICAT in a way that is fundamentally incompatible with ids.server, ids.server will simply not work for you, I'm afraid.

**Comment by RKrahl** [comment]
… continued:

If after all that sermon you still want to use ids.server, here is what I can suggest you to do:

+ as a general rule, if files are missing from the storage, reflect that fact in ICAT by clearing the `location` attribute.  ids.server will then ignore that file and pretend it not to exist (which is after all true from ids.server's point of view).  I repeat that this will also be helpful to your users, if they have a mean to clearly distinguish between files that still exist and that can be downloaded and those that don't.

+ if you want to keep the previous value from the location attribute, store it as a `DatafileParameter`.

+ if you manage to reconstruct a missing file by whatever mean, no problem, add it back to the storage and reset the location to the old value.  ids.server will immediately be able to serve that file.

+ for your legacy data, no need to restore and check them all at once.  You may as well use a policy of fixing the errors as they occur.  Just update to upcoming ids.server 1.10.0 (assuming it will be released with #98 merged).  As a result, datasets having missing files will fail to restore.  Having a look at the result from the `getServiceStatus` (watch for `failures` in that result) from time to time will yield a neat list of datasets having the problem.  For the datasets listed there, inspect them to verify that the issue is indeed the missing file, fix the content of ICAT to align it with the status in the storage and call `reset` for the datasets.  From that point on, the fixed datasets will be served normally.

**Comment by antolinos** [comment]
> This will even (apparently) work: the user makes the `getData` call, ids.server will reply with HTTP Ok (200) and a zip file in the body. But if the user inspects the downloaded file closer, he or she will get:
> 
> ```
> $ file /tmp/testdata.zip  
> /tmp/testdata.zip: Zip archive data, at least v2.0 to extract Zip archive data, at least v2.0 to extract
> $ unzip -l /tmp/testdata.zip
> Archive:  /tmp/testdata.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of /tmp/testdata.zip or
>         /tmp/testdata.zip.zip, and cannot find /tmp/testdata.zip.ZIP, period.
> ```
> See #100 for an explanation. Note that this (partial) download may still be large. I guess your users will not be very happy if they waited an hour for downloading a few tens of GB just to find out that all they got in the end is a very large, but unusable pile of bits.

Indeed, this is not good but not blocking as it could be solved with a simple check if the file exists at the ids side before streaming, right?

> * if you want to keep the previous value from the location attribute, store it as a `DatafileParameter`.

Drawback of this approach is that Datafile table is huge. By adding location as datafileParameter would mean to double the volume of space required for the largest table of the DB.


> I'm afraid, option "a", sticking with ids.server 1.9.0, will not work for you.

In any case, it was not a long term solution :(

**Comment by stuartpullinger** [comment]
It seems to me that @RKrahl feels the behaviour under discussion is a bug while @antolinos feels this is a desirable feature. It seems unfair to me to change previous behaviour on a minor release - even if that behaviour was unintentional.

May I suggest a compromise to prevent holding up this release? Is it possible to add a configuration option which controls this behaviour? The option could be named something like 'Unsafe-ignore-missing-files-on-restore' and could even be left undocumented if you really want to discourage it's use. The DsRestorer could check for the presence of this option in the constructor (as it does for other options) and default to False if it is missing. The catch clause could check for this option: if true, log an error; if false, rethrow the exception. I don't expect any performance degradation from this approach and only those who need to use it need to know about it. I'm happy to provide a patch if you approve.

This doesn't solve issue #100 so a similar compromise might be needed there.

**Comment by antolinos** [comment]
> This doesn't solve issue #100 so a similar compromise might be needed there.

I wonder if Unsafe-ignore-missing-files-on-restore == true then just a check of the existence of the file before putting into nameToLocalMap would be enough: 
https://github.com/icatproject/ids.server/blob/bbaa368d418c380ea3284320338c22d074d9eb5e/src/main/java/org/icatproject/ids/thread/DsRestorer.java#L75

**Comment by antolinos** [comment]
@stuartpullinger @RKrahl 

I confirm that IDS throws an error when calling to the method getData and a file is missing:
java.nio.file.NoSuchFileException: /data/icat/main/186715693/test.edf
